name: BrandBlocker
version: ${project.version}
main: dev.victormenacho.brandblocker.BrandBlocker
authors: [ Menacho ]
description: Block any client brand easily.
website: victormenacho.dev
api-version: 1.14
commands:
  brandblocker:
    description: BrandBlocker main command.